### ISSUE TITLE
Arrow items with 0 cooldown allow to mine too fast

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/CombatSystem#84]
The [_arrow items_](https://github.com/Terasology/CombatSystem/tree/develop/assets/prefabs/items/arrows) have a cool-down time of 0, which allows mining with them at light speed (e.g., in Light and Shadow).

https://github.com/Terasology/CombatSystem/blob/dfb49341544cda3868c58834d39b87e97953b695/assets/prefabs/items/arrows/stickArrowItem.prefab#L10

Changing this cool-down speed should fix the "fast mining" issue.

**Comment by jdrueckert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Playtest Findings](https://trello.com/c/X0iLPJA4/168-fix-playtest-findings)
